############

POST http://localhost:3000/api/developer/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eU51bWJlciI6IjIwMTUxMTA5OSIsImVtYWlsIjoib2NwaDIzQGdtYWlsLmNvbSIsImlkIjoiNWQ4ZmQ1MzVjOGQ4NmIyNDg0NTRhNmY3IiwidXNlck5hbWUiOiJPY3BoMjNAZ21haWwuY29tIiwicm9sZXMiOlsiU3R1ZGVudCIsIkRldmVsb3BlciIsIkRldmVsb3BlciJdLCJpYXQiOjE1Njk4ODMwNzEsImV4cCI6MTU2OTk2OTQ3MX0.2tIISacLjOr37IdVDKSjTJrUcdJjbZwhvxmJoclDa5g

{
  "companyName": "Ocph's COmputer",
  "author":"Yoseph Kungkung",
  "email":""
}

####


POST http://localhost:3000/api/developer/createapp HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eU51bWJlciI6IjIwMTUxMTA5OSIsImVtYWlsIjoib2NwaDIzQGdtYWlsLmNvbSIsImlkIjoiNWQ4ZmQ1MzVjOGQ4NmIyNDg0NTRhNmY3IiwidXNlck5hbWUiOiJPY3BoMjNAZ21haWwuY29tIiwicm9sZXMiOlsiU3R1ZGVudCIsIkRldmVsb3BlciIsIkRldmVsb3BlciJdLCJpYXQiOjE1Njk4ODMwNzEsImV4cCI6MTU2OTk2OTQ3MX0.2tIISacLjOr37IdVDKSjTJrUcdJjbZwhvxmJoclDa5g

{
    "appName":"Vote BEM 2",
    "version":"1.0.0",
    "description":"aplikasi pemilihan ketua bem"
}

####



Get http://localhost:3000/api/developer/apps HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eU51bWJlciI6IjIwMTUxMTA5OSIsImVtYWlsIjoib2NwaDIzQGdtYWlsLmNvbSIsImlkIjoiNWQ4ZmQ1MzVjOGQ4NmIyNDg0NTRhNmY3IiwidXNlck5hbWUiOiJPY3BoMjNAZ21haWwuY29tIiwicm9sZXMiOlsiU3R1ZGVudCJdLCJpYXQiOjE1Njk3ODgwODksImV4cCI6MTU2OTg3NDQ4OX0.8IigYbLJmsZvK3Q58KiSHgatXOIwDOvoWOgZoe9cjJs

####




Get http://localhost:3000/api/developer/app/5d912df966ca9608f026c537 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eU51bWJlciI6IjIwMTUxMTA5OSIsImVtYWlsIjoib2NwaDIzQGdtYWlsLmNvbSIsImlkIjoiNWQ4ZmQ1MzVjOGQ4NmIyNDg0NTRhNmY3IiwidXNlck5hbWUiOiJPY3BoMjNAZ21haWwuY29tIiwicm9sZXMiOlsiU3R1ZGVudCJdLCJpYXQiOjE1Njk3ODgwODksImV4cCI6MTU2OTg3NDQ4OX0.8IigYbLJmsZvK3Q58KiSHgatXOIwDOvoWOgZoe9cjJs
appKey: U2FsdGVkX1+a0z8ZMqy2LqBHl4cuBLnHcSb6i2f/pA4=

####


Get http://localhost:3000/api/developer/newappkey/5d912df966ca9608f026c537 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eU51bWJlciI6IjIwMTUxMTA5OSIsImVtYWlsIjoib2NwaDIzQGdtYWlsLmNvbSIsImlkIjoiNWQ4ZmQ1MzVjOGQ4NmIyNDg0NTRhNmY3IiwidXNlck5hbWUiOiJPY3BoMjNAZ21haWwuY29tIiwicm9sZXMiOlsiU3R1ZGVudCJdLCJpYXQiOjE1Njk3ODgwODksImV4cCI6MTU2OTg3NDQ4OX0.8IigYbLJmsZvK3Q58KiSHgatXOIwDOvoWOgZoe9cjJs


####