############

POST http://localhost:3000/register/create HTTP/1.1
Content-Type: application/json

{
  "npm": "201511099",
  "userName": "Ocph23",
  "email": "Ocph23@gmail.com",
  "password": "Sony@77",
  "confirmPassword": "Sony@77",
  "role":"Student",
  "identityNumber":"201511099"
}

####

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

 {"userName": "Ocph23@gmail.com", "password": "Sony@77"}

####

GET  http://localhost:3000/auth/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eU51bWJlciI6IjIwMTUxMTA5OSIsImVtYWlsIjoib2NwaDIzQGdtYWlsLmNvbSIsImlkIjoiNWQ4ZmQ1MzVjOGQ4NmIyNDg0NTRhNmY3IiwidXNlck5hbWUiOiJPY3BoMjNAZ21haWwuY29tIiwicm9sZXMiOlsiU3R1ZGVudCJdLCJpYXQiOjE1Njk3MTQ5MjMsImV4cCI6MTU2OTgwMTMyM30.Je3gP3yrNlDK4e2jh5UTsEMlqMwDHvny-fPrmCsIZs8
####

GET  http://localhost:3000/auth/IsLoged HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eU51bWJlciI6IjIwMTUxMTA5OSIsImVtYWlsIjoib2NwaDIzQGdtYWlsLmNvbSIsImlkIjoiNWQ4ZmQ1MzVjOGQ4NmIyNDg0NTRhNmY3IiwidXNlck5hbWUiOiJPY3BoMjNAZ21haWwuY29tIiwicm9sZXMiOlsiU3R1ZGVudCJdLCJpYXQiOjE1Njk3MTQ5MjMsImV4cCI6MTU2OTgwMTMyM30.Je3gP3yrNlDK4e2jh5UTsEMlqMwDHvny-fPrmCsIZs8
#####